package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/dto"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"
	"github.com/QuantumNous/new-api/types"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

// applyUpstreamContentLength populates req.ContentLength when the upstream
// body is wrapped in a BodyStorage (see relay/common/outbound_body.go).
//
// net/http.NewRequest only auto-detects ContentLength for *bytes.Reader,
// *bytes.Buffer and *strings.Reader. When the body is a type-erased io.Reader
// (which is the case for ReaderOnly(BodyStorage)), the Content-Length header
// would otherwise be omitted, forcing chunked transfer encoding and breaking
// some upstreams that require an explicit Content-Length.
func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

type overloadLeaseResponseBody struct {
	io.ReadCloser
	lease *service.OverloadLease
	once  sync.Once
}

func (body *overloadLeaseResponseBody) Close() error {
	err := body.ReadCloser.Close()
	body.once.Do(func() {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		defer cancel()
		body.lease.Release(ctx)
	})
	return err
}

func attachOverloadLeaseToResponse(c *gin.Context, resp *http.Response) {
	lease := service.DetachChannelOverloadLease(c)
	if lease == nil {
		return
	}
	if resp == nil || resp.Body == nil {
		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		defer cancel()
		lease.Release(ctx)
		return
	}
	resp.Body = &overloadLeaseResponseBody{ReadCloser: resp.Body, lease: lease}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func buildHeaderRewriteInput(info *common.RelayInfo, c *gin.Context) common.HeaderRewriteInput {
	input := common.HeaderRewriteInput{}
	if info != nil {
		input.ChannelSetting = info.ChannelSetting
		input.LegacyOverride = common.GetEffectiveHeaderOverride(info)
		input.APIKey = info.ApiKey
		input.RequestID = info.RequestId
		input.IsChannelTest = info.IsChannelTest
	}
	if c != nil && c.Request != nil {
		input.IncomingHeaders = c.Request.Header
		input.AllowClientHeader = true
		if input.RequestID == "" {
			input.RequestID = c.GetString(common2.RequestIdKey)
		}
	}
	return input
}

func ApplyHeaderRewrite(headers http.Header, info *common.RelayInfo, c *gin.Context) error {
	err := common.ResolveAndApplyHeaderRewrite(headers, buildHeaderRewriteInput(info, c))
	if err != nil {
		return types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
	}
	return nil
}

func applyHeaderRewriteToRequest(req *http.Request, info *common.RelayInfo, c *gin.Context) error {
	err := common.ResolveAndApplyHeaderRewriteToRequest(req, buildHeaderRewriteInput(info, c))
	if err != nil {
		return types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
	}
	return nil
}

func ValidateChannelRequestMode(info *common.RelayInfo) error {
	if info == nil || info.ChannelMeta == nil || info.IsChannelTest || info.ClientRequestMode == types.RequestModeUnknown {
		return nil
	}
	settings := info.ChannelOtherSettings
	disabled := settings.DisableNonStream
	errorCode := types.ErrorCodeChannelNonStreamDisabled
	if info.ClientRequestMode == types.RequestModeStream {
		disabled = settings.DisableStream
		errorCode = types.ErrorCodeChannelStreamDisabled
	}
	if !disabled {
		return nil
	}
	return types.NewErrorWithStatusCode(
		fmt.Errorf("the selected channel does not accept %s requests", info.ClientRequestMode.String()),
		errorCode,
		http.StatusServiceUnavailable,
	)
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if err := ValidateChannelRequestMode(info); err != nil {
		return nil, err
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	if err := applyHeaderRewriteToRequest(req, info, c); err != nil {
		return nil, err
	}
	if finalizer, ok := a.(RequestHeaderFinalizer); ok {
		if err := finalizer.FinalizeRequestHeader(c, req, info); err != nil {
			return nil, fmt.Errorf("finalize request header failed: %w", err)
		}
	}
	if err := service.CommitChannelOverloadLease(c); err != nil {
		return nil, types.NewError(err, types.ErrorCodeChannelOverloaded, types.ErrOptionWithStatusCode(http.StatusServiceUnavailable), types.ErrOptionWithSkipRetry())
	}
	if !service.IsChannelOverloadLeaseControllerOwned(c) {
		defer service.ReleaseChannelOverloadLease(c)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		service.ReleaseChannelOverloadLease(c)
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	attachOverloadLeaseToResponse(c, resp)
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if err := ValidateChannelRequestMode(info); err != nil {
		return nil, err
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	if err := applyHeaderRewriteToRequest(req, info, c); err != nil {
		return nil, err
	}
	if err := service.CommitChannelOverloadLease(c); err != nil {
		return nil, types.NewError(err, types.ErrorCodeChannelOverloaded, types.ErrOptionWithStatusCode(http.StatusServiceUnavailable), types.ErrOptionWithSkipRetry())
	}
	if !service.IsChannelOverloadLeaseControllerOwned(c) {
		defer service.ReleaseChannelOverloadLease(c)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		service.ReleaseChannelOverloadLease(c)
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	attachOverloadLeaseToResponse(c, resp)
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	if err := ValidateChannelRequestMode(info); err != nil {
		return nil, err
	}
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	if err := ApplyHeaderRewrite(targetHeader, info, c); err != nil {
		return nil, err
	}
	if err := service.CommitChannelOverloadLease(c); err != nil {
		return nil, types.NewError(err, types.ErrorCodeChannelOverloaded, types.ErrOptionWithStatusCode(http.StatusServiceUnavailable), types.ErrOptionWithSkipRetry())
	}
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		service.ReleaseChannelOverloadLease(c)
	} else if lease := service.DetachChannelOverloadLease(c); lease != nil {
		c.Set("websocket_overload_lease", lease)
	}
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) (context.CancelFunc, <-chan struct{}) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})

	gopool.Go(func() {
		defer close(done)
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	if err := ValidateChannelRequestMode(info); err != nil {
		return nil, err
	}
	return doRequest(c, req, info)
}

var errResponseHeaderTimeout = errors.New("upstream response header timeout")
var errResponseBodyTimeout = errors.New("upstream response body timeout")

type responseHeaderWait struct {
	mu         sync.Mutex
	startedAt  time.Time
	cancel     context.CancelCauseFunc
	timer      *time.Timer
	generation uint64
	active     bool
	expired    bool
}

var activeResponseHeaderWaits = struct {
	sync.Mutex
	byChannel map[int]map[*responseHeaderWait]struct{}
}{
	byChannel: make(map[int]map[*responseHeaderWait]struct{}),
}

func (w *responseHeaderWait) reconfigure(timeout time.Duration) {
	w.mu.Lock()
	if !w.active || w.expired {
		w.mu.Unlock()
		return
	}
	w.generation++
	generation := w.generation
	if w.timer != nil {
		w.timer.Stop()
		w.timer = nil
	}
	if timeout <= 0 {
		w.mu.Unlock()
		return
	}

	remaining := timeout - time.Since(w.startedAt)
	if remaining <= 0 {
		w.expired = true
		w.active = false
		cancel := w.cancel
		w.mu.Unlock()
		cancel(errResponseHeaderTimeout)
		return
	}
	w.timer = time.AfterFunc(remaining, func() {
		w.mu.Lock()
		if !w.active || w.expired || w.generation != generation {
			w.mu.Unlock()
			return
		}
		w.expired = true
		w.active = false
		cancel := w.cancel
		w.mu.Unlock()
		cancel(errResponseHeaderTimeout)
	})
	w.mu.Unlock()
}

func (w *responseHeaderWait) stop() bool {
	w.mu.Lock()
	w.active = false
	w.generation++
	if w.timer != nil {
		w.timer.Stop()
		w.timer = nil
	}
	expired := w.expired
	w.mu.Unlock()
	return expired
}

func registerResponseHeaderWait(channelID int, wait *responseHeaderWait, initialTimeout time.Duration) {
	if channelID <= 0 {
		wait.reconfigure(initialTimeout)
		return
	}
	activeResponseHeaderWaits.Lock()
	waits := activeResponseHeaderWaits.byChannel[channelID]
	if waits == nil {
		waits = make(map[*responseHeaderWait]struct{})
		activeResponseHeaderWaits.byChannel[channelID] = waits
	}
	wait.reconfigure(initialTimeout)
	waits[wait] = struct{}{}
	activeResponseHeaderWaits.Unlock()
}

func unregisterResponseHeaderWait(channelID int, wait *responseHeaderWait) {
	if channelID <= 0 {
		return
	}
	activeResponseHeaderWaits.Lock()
	waits := activeResponseHeaderWaits.byChannel[channelID]
	delete(waits, wait)
	if len(waits) == 0 {
		delete(activeResponseHeaderWaits.byChannel, channelID)
	}
	activeResponseHeaderWaits.Unlock()
}

func refreshActiveResponseHeaderTimeout(channelID int, timeout time.Duration) {
	if channelID <= 0 {
		return
	}
	activeResponseHeaderWaits.Lock()
	waits := make([]*responseHeaderWait, 0, len(activeResponseHeaderWaits.byChannel[channelID]))
	for wait := range activeResponseHeaderWaits.byChannel[channelID] {
		waits = append(waits, wait)
	}
	activeResponseHeaderWaits.Unlock()
	for _, wait := range waits {
		wait.reconfigure(timeout)
	}
}

// RefreshActiveResponseHeaderTimeout applies a saved channel timeout to
// requests that are already waiting for response headers. Response bodies are
// unaffected because waits are unregistered as soon as headers arrive.
func RefreshActiveResponseHeaderTimeout(channelID int, settings *dto.ResponseHeaderTimeoutSettings) {
	timeout := time.Duration(dto.DefaultResponseHeaderTimeoutSeconds) * time.Second
	if settings != nil {
		normalized := settings.Normalize()
		if !normalized.Enabled {
			timeout = 0
		} else {
			timeout = time.Duration(normalized.TimeoutSeconds) * time.Second
		}
	}
	refreshActiveResponseHeaderTimeout(channelID, timeout)
}

type responseBodyCancelReadCloser struct {
	io.ReadCloser
	cancel context.CancelCauseFunc
}

type responseBodyIdleReadCloser struct {
	io.ReadCloser
	timeout  time.Duration
	mu       sync.Mutex
	timer    *time.Timer
	timedOut bool
	closed   bool
	closeErr error
}

func newResponseBodyIdleReadCloser(body io.ReadCloser, timeout time.Duration) io.ReadCloser {
	if body == nil || timeout <= 0 {
		return body
	}
	return &responseBodyIdleReadCloser{ReadCloser: body, timeout: timeout}
}

func (b *responseBodyIdleReadCloser) timeoutError() error {
	return types.NewErrorWithStatusCode(
		fmt.Errorf("upstream response body produced no data for %d seconds: %w", int(b.timeout/time.Second), errResponseBodyTimeout),
		types.ErrorCodeChannelResponseBodyTimeout,
		http.StatusGatewayTimeout,
	)
}

func (b *responseBodyIdleReadCloser) Read(p []byte) (int, error) {
	b.mu.Lock()
	if b.closed {
		timedOut := b.timedOut
		b.mu.Unlock()
		if timedOut {
			return 0, b.timeoutError()
		}
		return 0, http.ErrBodyReadAfterClose
	}
	if b.timer == nil {
		b.timer = time.AfterFunc(b.timeout, b.expire)
	} else {
		b.timer.Reset(b.timeout)
	}
	b.mu.Unlock()

	n, err := b.ReadCloser.Read(p)

	b.mu.Lock()
	timedOut := b.timedOut
	if err != nil && b.timer != nil {
		b.timer.Stop()
	} else if n > 0 && b.timer != nil {
		b.timer.Reset(b.timeout)
	}
	b.mu.Unlock()
	if timedOut {
		return n, b.timeoutError()
	}
	return n, err
}

func (b *responseBodyIdleReadCloser) expire() {
	b.mu.Lock()
	if b.closed {
		b.mu.Unlock()
		return
	}
	b.timedOut = true
	b.closed = true
	b.mu.Unlock()

	err := b.ReadCloser.Close()
	b.mu.Lock()
	b.closeErr = err
	b.mu.Unlock()
}

func (b *responseBodyIdleReadCloser) Close() error {
	b.mu.Lock()
	if b.timer != nil {
		b.timer.Stop()
	}
	if b.closed {
		err := b.closeErr
		b.mu.Unlock()
		return err
	}
	b.closed = true
	b.mu.Unlock()

	err := b.ReadCloser.Close()
	b.mu.Lock()
	b.closeErr = err
	b.mu.Unlock()
	return err
}

func (b *responseBodyCancelReadCloser) Close() error {
	err := b.ReadCloser.Close()
	b.cancel(nil)
	return err
}

func doRequestWithResponseHeaderTimeout(client *http.Client, req *http.Request, timeout time.Duration) (*http.Response, error) {
	return doRequestWithResponseHeaderTimeoutForChannel(client, req, 0, timeout)
}

func doRequestWithResponseHeaderTimeoutForChannel(client *http.Client, req *http.Request, channelID int, timeout time.Duration) (*http.Response, error) {
	timeoutContext, cancel := context.WithCancelCause(req.Context())
	wait := &responseHeaderWait{
		startedAt: time.Now(),
		cancel:    cancel,
		active:    true,
	}
	registerResponseHeaderWait(channelID, wait, timeout)

	resp, err := client.Do(req.WithContext(timeoutContext))
	unregisterResponseHeaderWait(channelID, wait)
	if wait.stop() || errors.Is(context.Cause(timeoutContext), errResponseHeaderTimeout) {
		if resp != nil && resp.Body != nil {
			_ = resp.Body.Close()
		}
		return nil, errResponseHeaderTimeout
	}
	if err != nil || resp == nil || resp.Body == nil {
		cancel(nil)
		return resp, err
	}
	resp.Body = &responseBodyCancelReadCloser{
		ReadCloser: resp.Body,
		cancel:     cancel,
	}
	return resp, nil
}

func responseHeaderTimeoutAppliesToRelay(info *common.RelayInfo) bool {
	if info == nil || info.ChannelMeta == nil || !info.IsStream {
		return false
	}
	switch info.RelayFormat {
	case types.RelayFormatOpenAI:
		if info.RelayMode != constant.RelayModeChatCompletions && info.RelayMode != constant.RelayModeCompletions {
			return false
		}
	case types.RelayFormatOpenAIResponses,
		types.RelayFormatOpenAIResponsesCompaction,
		types.RelayFormatClaude,
		types.RelayFormatGemini:
	default:
		return false
	}
	return true
}

func responseHeaderTimeoutForRelay(info *common.RelayInfo) time.Duration {
	if !responseHeaderTimeoutAppliesToRelay(info) {
		return 0
	}
	if info.ChannelOtherSettings.ResponseHeaderTimeout == nil {
		return time.Duration(dto.DefaultResponseHeaderTimeoutSeconds) * time.Second
	}

	settings := info.ChannelOtherSettings.ResponseHeaderTimeout.Normalize()
	if !settings.Enabled {
		return 0
	}
	return time.Duration(settings.TimeoutSeconds) * time.Second
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	service.CaptureRelayDebugHTTPRequest(c, req)
	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.NewProxyHttpClientWithFallback(info.ChannelSetting.Proxy, info.ChannelSetting.ProxyFallbackDirect)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger, pingerDone = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					<-pingerDone
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	responseHeaderTimeout := responseHeaderTimeoutForRelay(info)
	var resp *http.Response
	if responseHeaderTimeoutAppliesToRelay(info) {
		resp, err = doRequestWithResponseHeaderTimeoutForChannel(client, req, info.ChannelId, responseHeaderTimeout)
	} else {
		resp, err = client.Do(req)
	}
	if err != nil {
		if errors.Is(err, errResponseHeaderTimeout) {
			timeoutSeconds := int(responseHeaderTimeout / time.Second)
			timeoutErr := fmt.Errorf("upstream response headers were not received within %d seconds", timeoutSeconds)
			logger.LogWarn(c, timeoutErr.Error())
			return nil, types.NewErrorWithStatusCode(
				timeoutErr,
				types.ErrorCodeChannelResponseHeaderTimeout,
				http.StatusGatewayTimeout,
			)
		}
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	if !info.IsStream && !strings.HasPrefix(strings.ToLower(resp.Header.Get("Content-Type")), "text/event-stream") {
		resp.Body = newResponseBodyIdleReadCloser(resp.Body, time.Duration(common2.RelayResponseBodyTimeout)*time.Second)
	}
	service.CaptureRelayDebugHTTPResponse(c, resp)

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	if err := ValidateChannelRequestMode(info); err != nil {
		return nil, err
	}
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	if err := applyHeaderRewriteToRequest(req, info, c); err != nil {
		return nil, err
	}
	if err := service.CommitChannelOverloadLease(c); err != nil {
		return nil, types.NewError(err, types.ErrorCodeChannelOverloaded, types.ErrOptionWithStatusCode(http.StatusServiceUnavailable), types.ErrOptionWithSkipRetry())
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		service.ReleaseChannelOverloadLease(c)
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	attachOverloadLeaseToResponse(c, resp)
	return resp, nil
}
